Nama : William Yulio

NIM : 2301869840

Kelas : LD01

##Import Library

In [1]:
#Import Library
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, StandardScaler 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

### Load Dataset

In [2]:
feature = np.array([
        [0.08, 0.72], 
        [0.2, 0.5],
        [0.24, 0.30],
        [0.35, 0.35],
        [0.45, 0.50],
        [0.2, 0.48],
        [0.1, 1.0],
        [0.36, 0.75],
        [0.52, 0.24],
        [0.70, 0.65],
        [0.80, 0.26],
        [0.92, 0.45]]
    )

label= [1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1]

# Melakukan load dataset sesuai dengan data yang ada pada soal

In [3]:
weight = np.array([
          [1.2,0.38],
          [-1,1.3],
          [0.8,0.2],

])

bias = [
        [-0.456, -0.1, -1.2]
]
#Selanjutnya adalah hasil dari perhitungan bias dan weight didalam word

In [4]:

def sigmoid(var): 
    return(1 / (1 + np.exp(-var)))
#Forward Pass

def forward_pass(var, weight):
    result = np.matmul(var, weight) + bias
    return sigmoid(result)

transpose_weight = weight.transpose()
result = forward_pass(feature,transpose_weight)

print(result)


   # Setelah semua data sudah diolah maka data tersebut akan masuk kedalam fungsi fungsi tersebut
   # pertama tama kita akan melakukan transposer terhadap weight yang sudah kita kalkulasi sebelumnya di word, tujuannya adalah agar weight nantinya bisa dikalkulasi kedalam forward pass
   # selanjutnya saya membuat variabel result yang akan menampung hasil dari weight dan bias yang baru untuk layer selanjutnya dengan memanggil fungsi forward_pass()
   # Demikian yang saya bisa kerjakan untuk nomor 2 pak, untuk detail dari inisialisasi nilai weight dan bias di awal sudah saya tulis di word dengan judul "jawaban no.2"
   # Sebelumnya mohon maaf pak, kalau saya hanya bisa sampai ditahap mencari weight untuk dan bias untuk input menuju ke hidden layer saja, untuk hidden layer menuju ke output saya belum menemukan cara yang tepat pak

[[0.47841343 0.68048466 0.27051722]
 [0.49350037 0.58661758 0.28090034]
 [0.48650328 0.5124974  0.27928722]
 [0.524231   0.50125    0.29943286]
 [0.56807463 0.52497919 0.32300414]
 [0.49160079 0.58029877 0.28009307]
 [0.51099823 0.75026011 0.28495789]
 [0.5648821  0.62597786 0.3182122 ]
 [0.56443962 0.42360299 0.32387945]
 [0.65271617 0.5112481  0.37519353]
 [0.64629664 0.36308482 0.37566249]
 [0.69402403 0.39293301 0.40757484]]
